# Generated by Django 4.2.2 on 2023-06-21 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6edba71a-2c73-4045-8f87-947d053825d0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
