# Generated by Django 4.2.2 on 2023-06-21 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f02e57a-4fdd-4ef6-b95a-d7bdfa7b1817'), editable=False, primary_key=True, serialize=False),
        ),
    ]
